cargo-features = [
  "profile-overrides"
]

[workspace]
members = [
  "accounts",
  "accounts/tree-primitives",
  "beserial",
  "beserial/beserial_derive",
  "blockchain",
  "blockchain-albatross",
  "blockchain-base",
  "block-production",
  "block-production-albatross",
  "bls",
  "build-tools",
  "client",
  "collections",
  "consensus",
  "database",
  "fixed-unsigned",
  "genesis",
  "handel",
  "hash",
  "hash/hash_derive",
  "keys",
  "key-derivation",
  "lib",
  "macros",
  "mempool",
  "messages",
  "metrics-server",
  "mnemonic",
  "nano-sync",
  "network",
  "network-albatross",
  "network-interface",
  "network-mock",
  "peer-address",
  "primitives",
  "primitives/account",
  "primitives/block",
  "primitives/block-albatross",
  "primitives/block-base",
  "primitives/subscription",
  "primitives/transaction",
  "rpc-server",
  "tools",
  "transaction-builder",
  "utils",
  "validator",
  "validator-network-interface",
  "vrf",
  "wallet",
  "ws-rpc-server",
]

[profile.dev.package.nimiq-bls]
opt-level = 3

[profile.dev.package.nimiq-nano-sync]
opt-level = 3
