[package]
name = "nimiq-tendermint"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Tendermint implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs-albatross"
license = "Apache-2.0"

[dependencies]
futures = "0.3"
async-stream = "0.3.0"
async-trait = "0.1"
log = "0.4"

nimiq-hash = { path = "../hash", version = "0.1" }
nimiq-primitives = { path = "../primitives", version = "0.1", features = ["policy"] }
nimiq-block-albatross = { path = "../primitives/block-albatross", version = "0.1" }

[dev-dependencies]
beserial = { path = "../beserial", version = "0.1" }
tokio = { version = "0.2", features = ["rt-threaded","macros"] }
